version: '3.9'

services:
  skinet-client-prod:
    image: a2259687814/calendar-client-prod:latest
    container_name: calendar-client-prod
    restart: always
    pull_policy: always
    ports:
      - 32400:80
